# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Examples Apps
        run: |
          python3 -m unittest discover -s example/sample_app -p 'app.py'
      - name: Run Examples Apps With autoimport
        run: |
          python3 -m unittest discover -s example/sample_app_with_auto_import -p 'app.py'
